#!/usr/bin/env zsh

# ----------------------------- VARIÁVEIS ----------------------------- #
PPA_LIBRATBAG="ppa:libratbag-piper/piper-libratbag-git"
PPA_LUTRIS="ppa:lutris-team/lutris"
PPA_GRAPHICS_DRIVERS="ppa:graphics-drivers/ppa"

URL_WINE_KEY="https://dl.winehq.org/wine-builds/winehq.key"
URL_PPA_WINE="https://dl.winehq.org/wine-builds/ubuntu/"
URL_MSPACK="https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb"

PROGRAMS="/tmp/programs"

PACKAGES=(
  build-essential 
  curl
  dpkg
  flameshot
  flatpak 
  git
  gnome-software-plugin-flatpak
  guvcview
  libasound2-plugins:i386
  libdbus-1-3:i386
  libfreetype6:i386
  libgnutls30:i386
  libgpg-error0:i386
  libldap-2.4-2:i386
  libsdl2-2.0-0:i386
  libsqlite3-0:i386
  libssl-dev 
  libvulkan1
  libvulkan1:i386
  libxml2:i386
  lutris
  mint-meta-codecs
  piper
  ratbagd
  snapd
  software-properties-common
  speedtest-cli
  steam:i386
  steam-devices
  steam-installer
  qbittorrent
  unzip
  tree
  wine
  winff
  zsh
)

# ----------------------------- REQUISITOS ----------------------------- #
## Removendo travas eventuais do apt ##
sudo rm /var/lib/dpkg/lock-frontend
sudo rm /var/cache/apt/archives/lock

## Adicionando/Confirmando arquitetura de 32 bits ##
sudo dpkg --add-architecture i386

## Atualizando o repositório ##
sudo apt update -y

## Adicionando repositórios de terceiros e suporte a Snap (Driver Logitech, Lutris e Drivers Nvidia)##
sudo apt-add-repository "$PPA_LIBRATBAG" -y
sudo add-apt-repository "$PPA_LUTRIS" -y
sudo apt-add-repository "$PPA_GRAPHICS_DRIVERS" -y
wget -nc "$URL_WINE_KEY"
sudo apt-key add winehq.key
sudo apt-add-repository "deb $URL_PPA_WINE bionic main"

# ----------------------------- EXECUÇÃO ----------------------------- #
## Atualizando o repositório depois da adição de novos repositórios ##
sudo apt update -y

## Download e instalaçao de programas externos ##
mkdir "$PROGRAMS"
wget -c "$URL_MSPACK" -P "$PROGRAMS"

## Instalando pacotes .deb baixados na sessão anterior ##
sudo dpkg -i $PROGRAMS/*.deb

# Instalar programas no apt
for package in ${PACKAGES[@]}; do
  if ! dpkg -l | grep -q $package; then # Só instala se já não estiver instalado
    sudo apt install "$package" -y
  else
    echo "[INSTALADO] - $package"
  fi
done

sudo apt install --install-recommends winehq-stable wine-stable wine-stable-i386 wine-stable-amd64 -y

## Adicionando repositório Flathub ##
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo && 

## Instalando pacotes Flatpak ##
sudo flatpak install flathub com.spotify.Client -y

## Instalando pacotes Snap ##
sudo snap install photogimp

# ----------------------------- PÓS-INSTALAÇÃO ----------------------------- #
## Finalização, atualização e limpeza##
sudo apt update && sudo apt dist-upgrade -y
flatpak update
snap refresh
sudo apt autoclean
sudo apt autoremove -y
